version: '3.8'

services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=db-sef-password
      - MYSQL_USER=dafws
      - MYSQL_PASSWORD=7rVQW48ph2
      - MYSQL_DATABASE=daf-ws
      - TZ=America/Sao_Paulo      
    cap_add:
      - SYS_NICE
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  sef:
    build: ./sef
    restart: on-failure
    volumes:
      - ./sef/app:/app
    environment:
      - TZ=America/Sao_Paulo      
    ports:
      - "8080:8080"
    depends_on: 
      - redis
      - db

  paf:
    build: ./paf
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./paf/app:/app
    devices:
      - /dev:/dev
    privileged: true
    environment:
      - TZ=America/Sao_Paulo
      - FLASK_ENV=development 
    depends_on: 
      - sef
      - redis